### ISSUE TITLE
artiq 2.0 nist_qc2 gateware

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#512]
I'm using artiq 2.0.dev-py_482+gitc5ba44b on my virtual machine. 

If I try running the following code,

```python
from operator import itemgetter
from artiq.experiment import *


class TTL_Test(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl0")
    
    @kernel    
    def run(self):
        self.ttl0.output()
        delay(10*us)
        self.ttl0.on()
```

Nothing happens. I have set the tca and pca already. On the ttl panel, ttl0 is still listed as an input. I have the same issue on windows except that it identifies the mismatch between the gateware and software. 

```
WARNING:worker(4,ttl_start.py):artiq.coredevice.comm_generic:Mismatch between ga
teware (2.0.dev+482.gc5ba44b) and software (2.0.dev+460.gd90fd7d) versions
```

Has something changed with how the ttls are set from 1.1 to 2.0? If I use gateware  (1.1+14.gb5901db.dirty) the ttls seem to work. I'm wondering if I also messed up generating the gateware for 2.0 somehow. I followed the same steps as for the previous version as far as I can tell. I don't think the conda release included a bitstream.

**Comment by jordens** [comment]
https://m-labs.hk/artiq/manual-master/core_drivers_reference.html?highlight=output#artiq.coredevice.ttl.TTLInOut.output second line.

**Comment by r-srinivas** [comment]
If it hasn't changed, the code above should still work. Is my gateware messed up somehow?

**Comment by jordens** [comment]
There is no indication of that.
Insisting that wrong code should lead to consistent results seems the wrong approach here.

**Comment by r-srinivas** [comment]
Switching to the 1.1+ gateware I ran into an RTIO collision error without the delay. That didn't happen using the 2.0 gateware.

**Comment by r-srinivas** [comment]
I should add that I can't really set DDS` either. And even faulty code like this that should result in an underflow don't trigger any errors.

```python
from artiq.experiment import *

class DDS_Test(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("dds1")
        
    @kernel
    def run(self):
        self.dds1.init()
        self.dds1.set(200*MHz)
```

**Comment by r-srinivas** [comment]
I've attached the binaries I generated if that's maybe useful.
[binaries_0711.zip](https://github.com/m-labs/artiq/files/360126/binaries_0711.zip)

**Comment by jordens** [comment]
Try a few things from https://m-labs.hk/artiq/manual-master/getting_started_core.html

**Comment by jordens** [comment]
And if you want to compare with what we would build, just trigger a bitstream build yourself. I did it for you just now.

**Comment by r-srinivas** [comment]
What do you mean by trigger a bitstream build? If I try `conda install artiq-kc705-nist_qc2` it asks me to downgrade to artiq 1.0.

**Comment by jordens** [comment]
Trigger builds like this on IRC: http://irclog.whitequark.org/m-labs/2016-07-07#16919899

Triggered build: http://buildbot.m-labs.hk/builders/artiq-kc705-nist_qc2/builds/173

Package: artiq-kc705-nist_qc2-2.0.dev-py_482+gitc5ba44b

And there are also a few other 2.0.dev nist_qc2 bitstream packages that should work. Do you have your channels set up correctly?

**Comment by r-srinivas** [comment]
I'll look at those thanks. I haven't changed the device_db to what we were using before. Unless they've changed from 1.x to 2.0 they should be right.

**Comment by r-srinivas** [comment]
I tried flashing it from your version and I'm still seeing the same issues. Looking at the unit tests it looks like it's just skipping a lot of them. 

```
(artiq-dev-master) rabi@68810MAGTRAPVM:~/artiq-dev-master/artiq/artiq/test$ python3.5 -m unittest discover
.........sssssssssssssssssssssssssssssssssssssssss..s....s.s.........ss..........sssssssssssss.............sssssss.......s......
----------------------------------------------------------------------
Ran 128 tests in 37.629s

OK (skipped=67)
```

Which was the same for my bitstream.

**Comment by r-srinivas** [comment]
Strangely your bitstream only wrote until sector 73. 

The outputs were

m-labs bitstream
```
(artiq-dev-master) rabi@68810MAGTRAPVM:~/artiq-dev-master/artiq/artiq/test$ artiq_flash -t kc705 -m nist_qc2
Design name: b'top;UserID=0XFFFFFFFF;COMPRESS=TRUE;Version=2016.2\x00'
Partname b'7k325tffg900\x00'
Date b'2016/07/13\x00'
Time b'04:53:41\x00'
found binary data length: 4796684
Open On-Chip Debugger 0.10.0-dev-00251-g888d5a5 (2016-04-13-15:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 25000 kHz
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 25000 kHz
Info : JTAG tap: xc7.tap tap/device found: 0x43651093 (mfg: 0x049 (Xilinx), part: 0x3651, ver: 0x4)
loaded file /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/binaries/kc705-nist_qc2/bscan_spi_xc7k325t.bit to pld device 0 in 0s 622145us
Info : JTAG tap: xc7.tap tap/device found: 0x43651093 (mfg: 0x049 (Xilinx), part: 0x3651, ver: 0x4)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
flash 'jtagspi' found at 0x00000000
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 0 took 521 ms
Info : sector 1 took 522 ms
Info : sector 2 took 518 ms
Info : sector 3 took 528 ms
Info : sector 4 took 520 ms
Info : sector 5 took 533 ms
Info : sector 6 took 519 ms
Info : sector 7 took 518 ms
Info : sector 8 took 610 ms
Info : sector 9 took 613 ms
Info : sector 10 took 613 ms
Info : sector 11 took 619 ms
Info : sector 12 took 616 ms
Info : sector 13 took 601 ms
Info : sector 14 took 599 ms
Info : sector 15 took 618 ms
Info : sector 16 took 607 ms
Info : sector 17 took 605 ms
Info : sector 18 took 593 ms
Info : sector 19 took 602 ms
Info : sector 20 took 616 ms
Info : sector 21 took 611 ms
Info : sector 22 took 598 ms
Info : sector 23 took 617 ms
Info : sector 24 took 627 ms
Info : sector 25 took 647 ms
Info : sector 26 took 641 ms
Info : sector 27 took 636 ms
Info : sector 28 took 615 ms
Info : sector 29 took 650 ms
Info : sector 30 took 625 ms
Info : sector 31 took 620 ms
Info : sector 32 took 620 ms
Info : sector 33 took 619 ms
Info : sector 34 took 631 ms
Info : sector 35 took 642 ms
Info : sector 36 took 641 ms
Info : sector 37 took 610 ms
Info : sector 38 took 613 ms
Info : sector 39 took 610 ms
Info : sector 40 took 603 ms
Info : sector 41 took 615 ms
Info : sector 42 took 617 ms
Info : sector 43 took 608 ms
Info : sector 44 took 606 ms
Info : sector 45 took 601 ms
Info : sector 46 took 612 ms
Info : sector 47 took 624 ms
Info : sector 48 took 614 ms
Info : sector 49 took 624 ms
Info : sector 50 took 630 ms
Info : sector 51 took 644 ms
Info : sector 52 took 622 ms
Info : sector 53 took 626 ms
Info : sector 54 took 636 ms
Info : sector 55 took 647 ms
Info : sector 56 took 635 ms
Info : sector 57 took 623 ms
Info : sector 58 took 636 ms
Info : sector 59 took 632 ms
Info : sector 60 took 637 ms
Info : sector 61 took 644 ms
Info : sector 62 took 622 ms
Info : sector 63 took 624 ms
Info : sector 64 took 590 ms
Info : sector 65 took 586 ms
Info : sector 66 took 607 ms
Info : sector 67 took 604 ms
Info : sector 68 took 606 ms
Info : sector 69 took 601 ms
Info : sector 70 took 596 ms
Info : sector 71 took 595 ms
Info : sector 72 took 598 ms
Info : sector 73 took 624 ms
wrote 4849664 bytes from file /tmp/tmpy2xe3e3r in 295.147247s (16.046 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 4796684 bytes from file /tmp/tmpy2xe3e3r and flash bank 0 at offset 0x00000000 in 3.586304s (1306.153 KiB/s)
contents match
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 175 took 636 ms
wrote 65536 bytes from file /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/binaries/kc705-nist_qc2/bios.bin in 2.145107s (29.835 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 34824 bytes from file /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/binaries/kc705-nist_qc2/bios.bin and flash bank 0 at offset 0x00af0000 in 0.027846s (1221.282 KiB/s)
contents match
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 176 took 633 ms
Info : sector 177 took 640 ms
Info : sector 178 took 637 ms
Info : sector 179 took 642 ms
Info : sector 180 took 637 ms
wrote 327680 bytes from file /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/binaries/kc705-nist_qc2/runtime.fbi in 10.679165s (29.965 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 274272 bytes from file /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/binaries/kc705-nist_qc2/runtime.fbi and flash bank 0 at offset 0x00b00000 in 0.207168s (1292.882 KiB/s)
contents match
```

my bitstream

```
(artiq-dev-master) rabi@68810MAGTRAPVM:~/artiq-dev-master/binaries$ artiq_flash -d . -t kc705
Design name: b'top;UserID=0XFFFFFFFF;COMPRESS=TRUE;Version=2015.4\x00'
Partname b'7k325tffg900\x00'
Date b'2016/07/12\x00'
Time b'13:48:25\x00'
found binary data length: 5187176
Open On-Chip Debugger 0.10.0-dev-00251-g888d5a5 (2016-04-13-15:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 25000 kHz
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 25000 kHz
Info : JTAG tap: xc7.tap tap/device found: 0x43651093 (mfg: 0x049 (Xilinx), part: 0x3651, ver: 0x4)
loaded file /home/rabi/.migen/bscan_spi_xc7k325t.bit to pld device 0 in 0s 645488us
Info : JTAG tap: xc7.tap tap/device found: 0x43651093 (mfg: 0x049 (Xilinx), part: 0x3651, ver: 0x4)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
flash 'jtagspi' found at 0x00000000
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 0 took 507 ms
Info : sector 1 took 494 ms
Info : sector 2 took 498 ms
Info : sector 3 took 493 ms
Info : sector 4 took 493 ms
Info : sector 5 took 491 ms
Info : sector 6 took 484 ms
Info : sector 7 took 505 ms
Info : sector 8 took 603 ms
Info : sector 9 took 588 ms
Info : sector 10 took 586 ms
Info : sector 11 took 606 ms
Info : sector 12 took 583 ms
Info : sector 13 took 610 ms
Info : sector 14 took 604 ms
Info : sector 15 took 608 ms
Info : sector 16 took 626 ms
Info : sector 17 took 624 ms
Info : sector 18 took 620 ms
Info : sector 19 took 616 ms
Info : sector 20 took 615 ms
Info : sector 21 took 584 ms
Info : sector 22 took 591 ms
Info : sector 23 took 585 ms
Info : sector 24 took 583 ms
Info : sector 25 took 581 ms
Info : sector 26 took 587 ms
Info : sector 27 took 605 ms
Info : sector 28 took 611 ms
Info : sector 29 took 636 ms
Info : sector 30 took 625 ms
Info : sector 31 took 636 ms
Info : sector 32 took 610 ms
Info : sector 33 took 627 ms
Info : sector 34 took 635 ms
Info : sector 35 took 626 ms
Info : sector 36 took 625 ms
Info : sector 37 took 625 ms
Info : sector 38 took 621 ms
Info : sector 39 took 611 ms
Info : sector 40 took 610 ms
Info : sector 41 took 607 ms
Info : sector 42 took 612 ms
Info : sector 43 took 619 ms
Info : sector 44 took 615 ms
Info : sector 45 took 617 ms
Info : sector 46 took 622 ms
Info : sector 47 took 611 ms
Info : sector 48 took 614 ms
Info : sector 49 took 633 ms
Info : sector 50 took 615 ms
Info : sector 51 took 625 ms
Info : sector 52 took 606 ms
Info : sector 53 took 611 ms
Info : sector 54 took 624 ms
Info : sector 55 took 611 ms
Info : sector 56 took 592 ms
Info : sector 57 took 590 ms
Info : sector 58 took 601 ms
Info : sector 59 took 598 ms
Info : sector 60 took 614 ms
Info : sector 61 took 605 ms
Info : sector 62 took 599 ms
Info : sector 63 took 605 ms
Info : sector 64 took 606 ms
Info : sector 65 took 605 ms
Info : sector 66 took 615 ms
Info : sector 67 took 612 ms
Info : sector 68 took 624 ms
Info : sector 69 took 621 ms
Info : sector 70 took 627 ms
Info : sector 71 took 629 ms
Info : sector 72 took 627 ms
Info : sector 73 took 643 ms
Info : sector 74 took 626 ms
Info : sector 75 took 633 ms
Info : sector 76 took 628 ms
Info : sector 77 took 627 ms
Info : sector 78 took 628 ms
Info : sector 79 took 645 ms
wrote 5242880 bytes from file /tmp/tmpq6vuasfz in 167.384399s (30.588 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 5187176 bytes from file /tmp/tmpq6vuasfz and flash bank 0 at offset 0x00000000 in 3.866004s (1310.294 KiB/s)
contents match
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 175 took 641 ms
wrote 65536 bytes from file ./bios.bin in 2.127496s (30.082 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 35224 bytes from file ./bios.bin and flash bank 0 at offset 0x00af0000 in 0.026349s (1305.493 KiB/s)
contents match
auto erase enabled
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
Info : sector 176 took 635 ms
Info : sector 177 took 639 ms
Info : sector 178 took 638 ms
Info : sector 179 took 643 ms
Info : sector 180 took 637 ms
wrote 327680 bytes from file ./runtime.fbi in 10.600661s (30.187 KiB/s)
Info : Found flash device 'micron n25q128' (ID 0x0018ba20)
read 276620 bytes from file ./runtime.fbi and flash bank 0 at offset 0x00b00000 in 0.203278s (1328.903 KiB/s)
contents match
```

**Comment by r-srinivas** [comment]
I tried generating another bitstream and flashing the coredevice again but I still can't talk to the hardware. I'm using Vivado to generate the bitstream, has anything changed with regards to that in 2.0? But I guess that probably won't be the issue since I have the same issues with the bitstream from m-labs. I've attached the vivado log anyway in case that's useful.

[vivado_log_0713.txt](https://github.com/m-labs/artiq/files/361954/vivado_log_0713.txt)

**Comment by whitequark** [comment]
Are you running the most recent version of Vivado? We have recently checked in some code that tickled a toolchain bug, which resulted in broken bitstreams. I don't know the exact version where this is fixed, but @sbourdeauducq does.

**Comment by r-srinivas** [comment]
I'm currently using Vivado v2015.4.

**Comment by whitequark** [comment]
We're using Vivado 2016.2. And yes, the problem was exactly that there were no errors during synthesis or PAR, but the bitstream didn't work.

**Comment by sbourdeauducq** [comment]
Yes. Vivado 2014.2 will silently generate a broken bitstream, and 2016.2 will work.

**Comment by r-srinivas** [comment]
Okay, I'll try to get the latest version on this machine then. That still doesn't explain why I couldn't get it to work the version I got through conda yesterday, though, unless that was also generated using an older version of vivado.

**Comment by r-srinivas** [comment]
I tried installing it from conda today using

```
artiq                     2.0.dev         py_485+gitc0d5914    m-labs/label/dev
artiq-kc705-nist_qc2      2.0.dev         py_485+gitc0d5914    m-labs/label/dev
```

And I still don't seem to be able to talk to the hardware. Has the above gateware been verified to be working?

**Comment by jordens** [comment]
The unittests need a device db to discover the hardware. E.g. ` ARTIQ_ROOT=run python -m unittest discover -v artiq.test.coredevice` if there is a `device_db.pyon` in `run`.Otherwise they just skip all hardware tests.

Is the only symptom that the TTLs and DDSs don't seem to do anything nor give exceptions? Do the LEDs work? Do the inputs work?

Artiq 2.0 is not released. It is likely that that particular bitstream has never been tested.

**Comment by jordens** [comment]
LED works just fine here with 2.0.dev-py_485+gitc0d5914

**Comment by r-srinivas** [comment]
Was that using the nist_qc2 configuration? I tried the following code,

```python
from artiq.experiment import *

class LED(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("led")

    @kernel
    def run(self):
        self.led.output()
        delay(1*ms)
        self.led.on()
```

It doesn't work with the 2.0dev py_485+gitc0d5914 gateware but works with the 1.2 gateware. 

My device_db entry for the LED is

 ```
    "led": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 41}
    },
```

**Comment by jordens** [comment]
Yes. Obviously I am using the gateware in question.

Your code gives me the expected `RTIOUnderflow`. If I fix it (according to the links I gave you) it does exactly what I expect.

The LED is a `TTLOut`.

**Comment by r-srinivas** [comment]
Why would it trigger an underflow? Our RTIO clock period is 10 ns at 100 MHz. I can get the led to turn on without an underflow with 1.2 gateware but the 2.0 gateware does nothing. If I change the device_db entry to TTLOut, I see it listed as an out but I still can't turn it on. Even the override doesn't seem to do anything.

I should maybe point out here that our kc705 is using the the SMT-2 JTAG adaptor as discussed in #440. Not sure if that's the cause of the problem but I'll try with another KC705 we have.

**Comment by r-srinivas** [comment]
I tried flashing the bitstream on a separate KC705 that has its original SMT-1 adaptor and I still run into the same issue. The following code,

```python
from artiq.experiment import *

class LED(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("led")

    @kernel
    def run(self):
        self.led.output()
        delay(1*ms)
        self.led.on()
```

Runs using the 1.2 gateware and the LED turns on but not with the  2.0dev py_485+gitc0d5914 gateware.

**Comment by jordens** [comment]
If you want to debug this yourself, go ahead.
I am still waiting for you to execute the examples as described in the manual (see above) or the unittests with hardware (also see above).

**Comment by jordens** [comment]
And when you are swapping back and forth between 1.x and 2.x, can I assume that you either don't have an idle kernel or that you are swapping it as well?

**Comment by r-srinivas** [comment]
Looking at the unittest, using 2.0

```
(artiq-dev-master) rabi@68810MAGTRAPVM:~/artiq-dev-master/artiq/artiq/test$ ARTIQ_ROOT=/home/rabi/artiq-dev-master/artiq-magtrap python -m unittest discover -v artiq.test.coredevice
test_rtio_log (artiq.test.coredevice.test_analyzer.AnalyzerTest) ... ok
test_ttl_pulse (artiq.test.coredevice.test_analyzer.AnalyzerTest) ... ERROR
test_borrow (artiq.test.coredevice.test_cache.CacheTest) ... ERROR
test_get_empty (artiq.test.coredevice.test_cache.CacheTest) ... ERROR
test_put_get (artiq.test.coredevice.test_cache.CacheTest) ... ERROR
test_replace (artiq.test.coredevice.test_cache.CacheTest) ... ERROR
test_default_arg (artiq.test.coredevice.test_embedding.DefaultArgTest) ... ok
test_1MB (artiq.test.coredevice.test_embedding.LargePayloadTest) ... ok
test_args (artiq.test.coredevice.test_embedding.RPCTest) ... /home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full(10, 20) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
ok
test_None (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_array (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_bool (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_float (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_int (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_list (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_object (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_object_list (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_str (artiq.test.coredevice.test_embedding.RoundtripTest) ... ok
test_i2c_switch (artiq.test.coredevice.test_i2c.I2CTest) ... ERROR
test_exceptions (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... <artiq>/test/coredevice/test_portability.py:150:25: warning: unreachable code
                        self._trace(12)
                        ^              
ok
test_math (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... 
ok
test_misc (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... 
ok
test_primes (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... 
ok
test_pulses (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... 
ok
test_rpc_exceptions (artiq.test.coredevice.test_portability.HostVsDeviceCase) ... ok
test_address_collision (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_clock_generator_loopback (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_collision (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_handover (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ok
test_handover_exception (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ok
test_loopback (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_loopback_count (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_pulse_rate (artiq.test.coredevice.test_rtio.CoredeviceTest)
Minimum interval for sustained TTL output switching ... ERROR
test_pulse_rate_dds (artiq.test.coredevice.test_rtio.CoredeviceTest)
Minimum interval for sustained DDS frequency switching ... 5.62375e-06
ok
test_sequence_error (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_time_keeps_running (artiq.test.coredevice.test_rtio.CoredeviceTest) ... skipped 'timings are dependent on CPU load and network conditions'
test_underflow (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ERROR
test_watchdog (artiq.test.coredevice.test_rtio.CoredeviceTest) ... ok
test_rpc_timing (artiq.test.coredevice.test_rtio.RPCTest) ... skipped 'timings are dependent on CPU load and network conditions'
test_busy (artiq.test.coredevice.test_spi.SPITest) ... ok
test_collision (artiq.test.coredevice.test_spi.SPITest) ... ok

======================================================================
ERROR: test_ttl_pulse (artiq.test.coredevice.test_analyzer.AnalyzerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'loop_in'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_analyzer.py", line 45, in test_ttl_pulse
    exp = self.create(CreateTTLPulse)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_analyzer.py", line 11, in build
    self.setattr_device("loop_in")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'loop_in'

======================================================================
ERROR: test_borrow (artiq.test.coredevice.test_cache.CacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'core_cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 42, in test_borrow
    exp = self.create(_Cache)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 9, in build
    self.setattr_device("core_cache")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'core_cache'

======================================================================
ERROR: test_get_empty (artiq.test.coredevice.test_cache.CacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'core_cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 27, in test_get_empty
    exp = self.create(_Cache)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 9, in build
    self.setattr_device("core_cache")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'core_cache'

======================================================================
ERROR: test_put_get (artiq.test.coredevice.test_cache.CacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'core_cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 31, in test_put_get
    exp = self.create(_Cache)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 9, in build
    self.setattr_device("core_cache")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'core_cache'

======================================================================
ERROR: test_replace (artiq.test.coredevice.test_cache.CacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'core_cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 36, in test_replace
    exp = self.create(_Cache)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_cache.py", line 9, in build
    self.setattr_device("core_cache")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'core_cache'

======================================================================
ERROR: test_i2c_switch (artiq.test.coredevice.test_i2c.I2CTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'i2c_switch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_i2c.py", line 24, in test_i2c_switch
    self.execute(I2CSwitch)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_i2c.py", line 10, in build
    self.setattr_device("i2c_switch")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'i2c_switch'

======================================================================
ERROR: test_address_collision (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'loop_in'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 326, in test_address_collision
    self.execute(AddressCollision)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 219, in build
    self.setattr_device("loop_in")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'loop_in'

======================================================================
ERROR: test_clock_generator_loopback (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'loop_clock_in'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 286, in test_clock_generator_loopback
    self.execute(ClockGeneratorLoopback)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 71, in build
    self.setattr_device("loop_clock_in")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'loop_clock_in'

======================================================================
ERROR: test_collision (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'ttl_out_serdes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 322, in test_collision
    self.execute(Collision)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 205, in build
    self.setattr_device("ttl_out_serdes")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'ttl_out_serdes'

======================================================================
ERROR: test_loopback (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'loop_in'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 279, in test_loopback
    self.execute(Loopback)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 47, in build
    self.setattr_device("loop_in")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'loop_in'

======================================================================
ERROR: test_loopback_count (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'loop_in'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 308, in test_loopback_count
    self.execute(LoopbackCount, npulses=npulses)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 153, in build
    self.setattr_device("loop_in")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'loop_in'

======================================================================
ERROR: test_pulse_rate (artiq.test.coredevice.test_rtio.CoredeviceTest)
Minimum interval for sustained TTL output switching
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'ttl_out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 292, in test_pulse_rate
    self.execute(PulseRate)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 91, in build
    self.setattr_device("ttl_out")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'ttl_out'

======================================================================
ERROR: test_sequence_error (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'ttl_out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 318, in test_sequence_error
    self.execute(SequenceError)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 191, in build
    self.setattr_device("ttl_out")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'ttl_out'

======================================================================
ERROR: test_underflow (artiq.test.coredevice.test_rtio.CoredeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 154, in get
    desc = self.get_desc(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 139, in get_desc
    desc = self.ddb.get(name)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/databases.py", line 27, in get
    return self.data.read[key]
KeyError: 'ttl_out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 314, in test_underflow
    self.execute(Underflow)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 142, in execute
    raise exn
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 131, in execute
    exp = self.create(cls, *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/hardware_testbench.py", line 115, in create
    *args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/test/coredevice/test_rtio.py", line 178, in build
    self.setattr_device("ttl_out")
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 268, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/language/environment.py", line 261, in get_device
    return self.__device_mgr.get(key)
  File "/home/rabi/anaconda3/envs/artiq-dev-master/lib/python3.5/site-packages/artiq/master/worker_db.py", line 157, in get
    .format(name)) from e
artiq.master.worker_db.DeviceError: Failed to get description of device 'ttl_out'

----------------------------------------------------------------------
Ran 41 tests in 7.758s

FAILED (errors=14, skipped=2)
(artiq-dev-master) rabi@68810MAGTRAPVM:~/artiq-dev-master/artiq/artiq/test$ 
```
Strangely after running the unittest, I tried starting the dashboard on windows and I can turn on the LED now and seemingly set TTLs and DDSes. I tried reflashing the board with the same gateware again, and had the same issues as before which disappeared upon running the unittest. I'm not sure what changed with the unittest.

**Comment by r-srinivas** [comment]
What do you mean by swapping the idle kernel? I've kept it as it is, which is just to turn the bdd ttl on. Do I have to change it every time I change the gateware version?

**Comment by sbourdeauducq** [comment]
Look at the seamless handover mechanism in 2.0.

**Comment by jordens** [comment]
Don't assume that "just turning on a ttl" is handled the same way under the hood forever. Yes. You need to update (compile and flash) the idle kernel every time something significant in the runtime or gateware or in your very own device_db.pyon changes. Since we don't track gateware/runtime API versions or your device_db.pyon, you need to do that yourself for the idle kernel. When you upgrade, just follow the manual again.

Your unittests look fine. Nothing unexpected is breaking. Please don't post this amount of text inline. Use a file or gist or something else. It makes this issue unreadable.

I don't know what "the other kc705" is. But yes. Fresh devices don't have an idle kernel.

Still waiting for you to follow and try the examples in the manual (see my third comment all the way at the top).

**Comment by sbourdeauducq** [comment]
@r-srinivas I guess that essentially you need to add a RTIO reset. Make sure you are reading the manual for 2.x (https://m-labs.hk/artiq/manual-master) and not for 1.x.

**Comment by r-srinivas** [comment]
Looks like the reset was it, thanks! Could that be added to the release notes, please? A brief description of it in the getting started with the core device section could also help.

**Comment by jordens** [comment]
Side note: trying the examples from the manual would have resolved this a week ago.

**Comment by r-srinivas** [comment]
Sad but true. I had taken a look at the release notes and didn't see it there so hadn't realised the explicit reset had been put in. Fortunately I only spent that one day last week on it and we were running the experiment after that. On the bright side at least I can continue with the 2.0 testing now.
